spring:
  datasource:
    url: jdbc:mysql://containers-us-west-193.railway.app:7683/railway?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: UYzdRvYTtQ0A0NRdxpAp

  sql:
    init:
      mode: always