
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: nyb-project
    description: Server for Norway Yacht Brokers
    author: Sergii Bezrukov
    version: '1.0'
spring:
  profiles:
    active: dev